### ISSUE TITLE
A little propose📄

### ISSUE THREAD

**Issue by bwnjnOEI** [yvrjsharma/JAX#1]
Thank you for writing such beautiful documents!

If the situation allows, I hope you can include some comparisons with `PyTorch` or `Tensorflow` in the same scenario. This would be an immense blessing for `JAX` beginners.

Looking forward to the next!
🚀

**Comment by yvrjsharma** [comment]
Hey, thanks for taking your time out for reading and suggesting. This is a good point. I am working on another smaller post around differences, will post soon.
